### ISSUE TITLE
The lucky blocks are doubling in score

### ISSUE THREAD

**Issue by NOTZepper** [denzelesh/PR1GameDenzelandFudail#2]
I think the incraments are set to 50 rather than 25, double check it for me would you?

**Comment by denzelesh** [comment]
Good spot, thanks for that. The game was basically running through the loop twice before moving the lucky block. I've now fixed it by ensuring the block moves position before a score is allocated. That way when the game loops again, the mamba will not be directly underneath the lucky block and score double points.
